title: Shawal Fida
description: Product Manager | Data Enthusiast | Generative AI Explorer
baseurl: ""
url: "https://shawalfida.github.io"

theme: jekyll-theme-minimal

# Social Links
linkedin_username: shawal-fida
github_username: shawalfida


